export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';

export const CONTACTS_LOADED = 'contacts_loaded';
export const CONTACTS_CHECKED = 'contact_checked';
export const CONTACTS_UNCHECKED = 'contact_unchecked';
export const CONTACTS_SELECTED = 'contacts_selected';
export const CONTACTS_SEARCH = 'contacts_search';
export const SELECT_FRIEND = 'SELECT_FRIEND';
export const SEARCH_FRIENDS = 'SEARCH_FRIENDS';
export const LOAD_FRIENDS = 'LOAD_FRIENDS';

/**
 * Author: Guilherme Borges Bastos
 * Scope: handling chat methods
 */
export const OPEN_CHAT = 'OPEN_CHAT';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const START_FETCHING_CHANNELS = 'START_FETCHING_CHANNELS';
export const RECEIVED_CHANNELS = 'RECEIVED_CHANNELS';
export const CHAT_MESSAGES_FETCH_SUCCESS = 'CHAT_MESSAGES_FETCH_SUCCESS';
export const START_FETCHING_CHANNELS_MESSAGES = 'START_FETCHING_CHANNELS_MESSAGES';

/**
 * Author: Alberto Schiabel
 * Scope: handling facebook auth flow
 */
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_FAIL = 'LOGIN_FACEBOOK_FAIL';
export const LOGIN_FACEBOOK_LOADING = 'LOGIN_FACEBOOK';

/**
 * Author: Alberto Schiabel
 * Scope: handling facebook API interactions after login
 */
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER = 'SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_SUCCESS';
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_SUCCESS = 'SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_SUCCESS';
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_FAIL = 'SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_FAIL';
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_CANCELLED = 'SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_CANCELLED';
export const SHARE_FB_LINK_WITH_PREDEFINED_COMMENT = 'SHARE_FB_LINK_WITH_PREDEFINED_COMMENT';
export const SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_SUCCESS = 'SHARE_FB_LINK_WITH_PREDEFINED_COMMENT';
export const SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_FAIL = 'SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_FAIL';
export const SEND_FB_APP_INVITE = 'SEND_FB_APP_INVITE';
export const SEND_FB_APP_INVITE_SUCCESS = 'SEND_FB_APP_INVITE_SUCCESS';
export const SEND_FB_APP_INVITE_FAIL = 'SEND_FB_APP_INVITE_FAIL';
export const SEND_FB_APP_INVITE_CANCELLED = 'SEND_FB_APP_INVITE_CANCELLED';
